[pyprland]
plugins = [
    "scratchpads",
]

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = false
hysteresis = 0.7

[scratchpads.spotify]
command = "spotify-launcher"
animation = "fromTop"
class = "spotify"
unfocus = "hide"
size = "75% 65%"
lazy = true
hysteresis = 0.7

[scratchpads.term]
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "65% 55%"
position = "20% 20%"
margin = 50
